### ISSUE TITLE
New background makes some icons unreadable

### ISSUE THREAD

**Issue by hax4dazy** [skjnldsv/pride#20]
The new background image causes some of the navbar items to become unreadable. It might be a good idea but I'm unsure if its possible to force these icons to either be white or also just rainbowify them.

![image](https://user-images.githubusercontent.com/16256978/235273623-e7024bee-587c-4145-b1cc-3768008dae8b.png)

**Comment by skjnldsv** [comment]
> rainbowify

I love this term :grin: 

It's a tricky one, because some users might still change this theme, so it's not possible to enforce something like that selectively (it's either all or none technically speaking)
I could change the primary colour from the current yellow to something a bit darker and it should revert the icons :thinking: 
Any suggestions? Another colour from the flag maybe?

**Comment by hax4dazy** [comment]
Maybe make it pink / blue like for trans people? That would the the lightest colour out there.

**Comment by skjnldsv** [comment]
Light colour means dark icons :)
The issue would still be here :(

**Comment by hax4dazy** [comment]
You could make it blood red but I'm not sure if that's so fun lmao. Maybe just go with black?
